# Generated by Django 5.0.6 on 2024-05-24 14:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_newrecipe_delete_recipecategory_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewRecipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
