# Generated by Django 5.0.6 on 2024-05-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_cookbookentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbookentry',
            name='saved_at',
        ),
    ]
