# Generated by Django 5.0.6 on 2024-05-26 09:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_delete_newrecipe_alter_recipe_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='static/images/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
